apiVersion: apps/v1
kind: Deployment
metadata:
  name: market
  labels:
    env: dev
    owner: Panasik
spec:
  selector:
    matchLabels:
      app: market
  template:
    metadata:
      labels:
        app: market
    spec:
      containers:
        - name: market
          image: vladislavpanasik/market:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: market-config
            - secretRef:
                name: market-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: market
spec:
  selector:
    app: market
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: market-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/market"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_BOOT_ADMIN_CLIENT_URL: "http://admin:9000"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
  KAFKA_HOST: "kafka:29092"
  SERVICE_IMAGE_UPLOAD_URL: "http://image:8082/upload/db"
---
apiVersion: v1
kind: Secret
metadata:
  name: market-secrets
stringData:
  SPRING_DATASOURCE_PASSWORD: cG9zdGdyZXM=
