{
 "title": "Endpoints, kafka, spring Data metrics Copy",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Average amount requests per seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate(http_client_requests_seconds_count[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 most used endpoints",
   "type": "timeseries",
   "description": "default time is 30 minutes but you can configure your",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, sum(rate(http_server_requests_seconds_count[30m])) by (uri))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average executing time of all requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_sum[30m]) / increase(http_server_requests_seconds_count[30m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total amount in kafka template ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(spring_kafka_template_seconds_count[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average executing  time of some endpoint in some service",
   "type": "timeseries",
   "description": "default value is /api/products in service market, but you can configure this",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_sum{uri=\"/api/products\",job=\"market\"}[30m]) / increase(http_server_requests_seconds_count{uri=\"/api/products\",job=\"market\"}[30m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total amount of requests from all services",
   "type": "timeseries",
   "description": "default time is 30 minutes, but you can configure your",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count[30m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}