spring:
  application:
    name: market

  datasource:
    url: jdbc:postgresql://localhost:5432/market
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
    locations: classpath:db/migration

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: consuming

  boot:
    admin:
      client:
        enabled: true
        auto-registration: true
        url: http://localhost:9000
        instance:
          name: ${spring.application.name:market}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    build:
      enabled: true
    java:
      enabled: true
    process:
      enabled: true

  metrics:
    enable:
      jvm: true
      system: true
      process: true

file:
  path: uploads

jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 30m
  refresh:
    lifetime: 10d

application:
  name: Market Service
  version: 1.0.1

server:
  port: 8081

service:
  image:
    upload:
      url: http://localhost:8082/upload/db

kafka:
  host: localhost:29092

redis:
  host: localhost
  port: 6379




