apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-image
  labels:
    env: {{ .Values.labels.env }}
    owner: {{ .Values.labels.owner }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName.image }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName.image }}
    spec:
      containers:
        - name: {{ .Values.container.image.name }}
          image: {{ .Values.image.image.repository }}:{{ .Values.image.image.tag }}
          ports:
            - containerPort: {{ .Values.container.image.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.appName.image }}-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName.image }}
spec:
  selector:
    app: {{ .Values.appName.image }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.image.port }}
      targetPort: {{ .Values.service.image.targetPort }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName.image }}-config
data:
  SPRING_DATA_MONGODB_URI: "{{ .Values.configMap.image.SPRING_DATA_MONGODB_URI }}"
  SPRING_DATA_MONGODB_DATABASE: "{{ .Values.configMap.image.SPRING_DATA_MONGODB_DATABASE }}"
  SPRING_BOOT_ADMIN_CLIENT_URL: "{{ .Values.configMap.image.SPRING_BOOT_ADMIN_CLIENT_URL }}"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.configMap.image.SPRING_KAFKA_BOOTSTRAP_SERVERS }}"
  KAFKA_HOST: "{{ .Values.configMap.image.KAFKA_HOST }}"
