apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: frontend
            port:
              number: {{ .Values.service.frontend.port }}
      - pathType: Prefix
        path: "/upload"
        backend:
          service:
            name: image
            port:
              number: {{ .Values.service.image.port }}
      - pathType: Prefix
        path: "/api/v1"
        backend:
          service:
            name: market
            port:
              number: {{ .Values.service.market.port }}